syntax on

set guicursor=
set noshowmatch
set relativenumber
set nohlsearch
set hidden
set noerrorbells
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set nu
set nowrap
set smartcase
set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile
set incsearch
set termguicolors
set scrolloff=8

" Start NERDTree. If a file is specified, move the cursor to its window.
autocmd stdinreadpre * let s:std_in=1
autocmd vimenter * NERDTree | if argc() > 0 || exists("s:std_in") | wincmd p | endif

" Set the theme to gruvbox
autocmd vimenter * ++nested colorscheme gruvbox
