name: Test
on:
  pull_request:
    branches:
      - main
      - next
      - alpha

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        id: setup-1
        uses: actions/checkout@v1

      - name: Install Nix
        id: setup-2
        uses: cachix/install-nix-action@v12
        with:
          skip_adding_nixpkgs_channel: true

      - name: Cachix
        id: setup-3
        uses: cachix/cachix-action@v8
        with:
          name: tal-casa-rel
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Download Nix Dependenices
        id: setup-4
        run: |
          nix-shell --pure shell.release.nix

  release:
    name: Release (Dry Run)
    needs: setup
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        id: release-1
        uses: actions/checkout@v1

      - name: Install Nix
        id: release-2
        uses: cachix/install-nix-action@v12

      - name: Cachix
        id: release-3
        uses: cachix/cachix-action@v8
        with:
          name: tal-casa-rel
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Install Node.js dependencies
        id: release-4
        run: |
          nix-shell --run "npm ci" shell.release.nix

      - name: Release
        id: release-5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          nix-shell --run "npm run release" shell.release.nix

  merge:
    name: Merge
    needs: release
    runs-on: ubuntu-18.04
    if: "contains(github.ref, 'main') || contains(github.ref, 'alpha')"
    steps:
      - name: Checkout
        id: merge-1
        uses: actions/checkout@v1

      - name: "Merge ${{ github.ref }} -> next"
        id: merge-2
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: next
          github_token: ${{ github.token }}


